# -*- coding: utf-8 -*-
"""globalpointer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gQ-I_xW_o-SlxgY6SNGXBTNSV4Fir8Zx
"""

# -*- coding: utf-8 -*-
"""
GlobalPointer NER with BIO tag output
- span-based GlobalPointer 학습
- 예측 결과를 BIO 태그로 변환
- raw prediction / confidence score / JSON 출력 지원
"""

import os
import json
import math
from dataclasses import dataclass
from typing import Dict, List, Tuple, Optional, Set

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from transformers import AutoModel
from torch.optim import AdamW


# =========================================================
# 0. CUDA 성능 옵션
# =========================================================
if torch.cuda.is_available():
    torch.backends.cuda.matmul.allow_tf32 = True
    torch.backends.cudnn.allow_tf32 = True
    torch.backends.cudnn.benchmark = True


# =========================================================
# 1. Config
# =========================================================
@dataclass
class Config:
    pretrained_model_name: str = "klue/roberta-base"

    train_json_path: str = "/content/klue_ner_globalpointer_train.jsonl"
    valid_json_path: str = "/content/klue_ner_globalpointer_valid.jsonl"

    batch_size: int = 64
    lr: float = 2e-5
    epochs: int = 5
    inner_dim: int = 64
    threshold: float = 0.0

    num_workers: int = 4
    max_grad_norm: float = 1.0
    use_amp: bool = True

    device: str = "cuda" if torch.cuda.is_available() else "cpu"


# =========================================================
# 2. JSON / JSONL 로드
# =========================================================
def load_jsonl_file(json_path: str) -> List[Dict]:
    if not os.path.exists(json_path):
        raise FileNotFoundError(f"파일을 찾을 수 없습니다: {json_path}")

    with open(json_path, "r", encoding="utf-8") as f:
        content = f.read().strip()

    if not content:
        raise ValueError(f"파일이 비어 있습니다: {json_path}")

    if content.startswith("["):
        try:
            data = json.loads(content)
            if not isinstance(data, list):
                raise ValueError("JSON은 리스트 형태여야 합니다.")
            return data
        except json.JSONDecodeError as e:
            raise ValueError(f"JSON 파싱 실패: {e}")

    data = []
    for line_num, line in enumerate(content.splitlines(), start=1):
        line = line.strip()
        if not line:
            continue
        try:
            data.append(json.loads(line))
        except json.JSONDecodeError as e:
            raise ValueError(f"{json_path} 파일의 {line_num}번째 줄 파싱 실패: {e}")

    return data


# =========================================================
# 3. label map 생성
# =========================================================
def build_label_maps(train_data: List[Dict], valid_data: List[Dict]) -> Tuple[Dict[str, int], Dict[int, str]]:
    entity_types = set()

    for dataset in [train_data, valid_data]:
        for sample in dataset:
            for ent in sample.get("entities", []):
                entity_types.add(ent["label"])

    entity_types = sorted(entity_types)
    label2id = {label: idx for idx, label in enumerate(entity_types)}
    id2label = {idx: label for label, idx in label2id.items()}
    return label2id, id2label


# =========================================================
# 4. Loss
# =========================================================
def multilabel_categorical_crossentropy(y_pred: torch.Tensor, y_true: torch.Tensor) -> torch.Tensor:
    """
    y_pred, y_true: (batch, ent_type_size, seq_len, seq_len)
    """
    y_pred = (1 - 2 * y_true) * y_pred
    y_pred_neg = y_pred - y_true * 1e12
    y_pred_pos = y_pred - (1 - y_true) * 1e12

    zeros = torch.zeros_like(y_pred[..., :1])
    y_pred_neg = torch.cat([y_pred_neg, zeros], dim=-1)
    y_pred_pos = torch.cat([y_pred_pos, zeros], dim=-1)

    neg_loss = torch.logsumexp(y_pred_neg, dim=-1)
    pos_loss = torch.logsumexp(y_pred_pos, dim=-1)

    return (neg_loss + pos_loss).mean()


# =========================================================
# 5. RoPE 캐시
# =========================================================
class RoPEPositionEncoding(nn.Module):
    def __init__(self, max_seq_len: int, inner_dim: int):
        super().__init__()
        self.max_seq_len = max_seq_len
        self.inner_dim = inner_dim

        position_ids = torch.arange(0, max_seq_len, dtype=torch.float).unsqueeze(-1)
        indices = torch.arange(0, inner_dim // 2, dtype=torch.float)
        indices = torch.pow(10000, -2 * indices / inner_dim)

        embeddings = position_ids * indices
        sin_embeddings = torch.sin(embeddings)
        cos_embeddings = torch.cos(embeddings)

        pos_emb = torch.stack([sin_embeddings, cos_embeddings], dim=-1).reshape(max_seq_len, inner_dim)
        self.register_buffer("pos_emb", pos_emb, persistent=False)

    def forward(self, seq_len: int, batch_size: int) -> torch.Tensor:
        return self.pos_emb[:seq_len].unsqueeze(0).expand(batch_size, -1, -1)


def apply_rope(x: torch.Tensor, pos_emb: torch.Tensor) -> torch.Tensor:
    """
    x: (batch, seq_len, ent_type_size, inner_dim)
    pos_emb: (batch, seq_len, inner_dim)
    """
    cos_pos = pos_emb[..., 1::2].repeat_interleave(2, dim=-1)
    sin_pos = pos_emb[..., ::2].repeat_interleave(2, dim=-1)

    x2 = torch.stack([-x[..., 1::2], x[..., ::2]], dim=-1).reshape_as(x)
    return x * cos_pos.unsqueeze(2) + x2 * sin_pos.unsqueeze(2)


# =========================================================
# 6. GlobalPointer Head
# =========================================================
class GlobalPointer(nn.Module):
    def __init__(self, hidden_size: int, ent_type_size: int, inner_dim: int, max_seq_len: int = 512, use_rope: bool = True):
        super().__init__()
        self.ent_type_size = ent_type_size
        self.inner_dim = inner_dim
        self.use_rope = use_rope
        self.dense = nn.Linear(hidden_size, ent_type_size * inner_dim * 2)

        if use_rope:
            self.rope = RoPEPositionEncoding(max_seq_len=max_seq_len, inner_dim=inner_dim)

    def forward(self, last_hidden_state: torch.Tensor, attention_mask: torch.Tensor) -> torch.Tensor:
        batch_size, seq_len, _ = last_hidden_state.size()

        outputs = self.dense(last_hidden_state)
        outputs = outputs.view(batch_size, seq_len, self.ent_type_size, self.inner_dim * 2)
        qw, kw = outputs[..., :self.inner_dim], outputs[..., self.inner_dim:]

        if self.use_rope:
            pos_emb = self.rope(seq_len=seq_len, batch_size=batch_size)
            qw = apply_rope(qw, pos_emb)
            kw = apply_rope(kw, pos_emb)

        logits = torch.einsum("bmhd,bnhd->bhmn", qw, kw)
        logits = logits / math.sqrt(self.inner_dim)

        mask1 = attention_mask.unsqueeze(1).unsqueeze(3)
        mask2 = attention_mask.unsqueeze(1).unsqueeze(2)
        pad_mask = mask1 * mask2
        logits = logits * pad_mask - (1 - pad_mask) * 1e12

        tril_mask = torch.tril(
            torch.ones(seq_len, seq_len, device=logits.device, dtype=logits.dtype),
            diagonal=-1
        )
        logits = logits - tril_mask.unsqueeze(0).unsqueeze(0) * 1e12

        return logits


# =========================================================
# 7. Encoder + GlobalPointer
# =========================================================
class BertGlobalPointerForNER(nn.Module):
    def __init__(self, pretrained_model_name: str, ent_type_size: int, inner_dim: int, max_seq_len: int = 512):
        super().__init__()
        self.encoder = AutoModel.from_pretrained(pretrained_model_name)
        hidden_size = self.encoder.config.hidden_size

        self.global_pointer = GlobalPointer(
            hidden_size=hidden_size,
            ent_type_size=ent_type_size,
            inner_dim=inner_dim,
            max_seq_len=max_seq_len,
            use_rope=True
        )

    def forward(self, input_ids, attention_mask, token_type_ids=None, labels=None):
        encoder_kwargs = {
            "input_ids": input_ids,
            "attention_mask": attention_mask,
        }

        if token_type_ids is not None:
            try:
                outputs = self.encoder(
                    input_ids=input_ids,
                    attention_mask=attention_mask,
                    token_type_ids=token_type_ids
                )
            except TypeError:
                outputs = self.encoder(**encoder_kwargs)
        else:
            outputs = self.encoder(**encoder_kwargs)

        last_hidden_state = outputs.last_hidden_state
        logits = self.global_pointer(last_hidden_state, attention_mask)

        result = {"logits": logits}
        if labels is not None:
            result["loss"] = multilabel_categorical_crossentropy(logits, labels)
        return result


# =========================================================
# 8. Dataset
# =========================================================
class LocalJsonlNERDataset(Dataset):
    def __init__(
        self,
        data: List[Dict],
        label2id: Dict[str, int],
        split_name: str
    ):
        self.data = data
        self.label2id = label2id
        self.ent_type_size = len(label2id)
        self.split_name = split_name

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        sample = self.data[idx]

        text = sample["text"]
        input_ids = sample["input_ids"]
        attention_mask = sample["attention_mask"]
        token_type_ids = sample.get("token_type_ids", None)
        entities = sample.get("entities", [])

        seq_len = len(input_ids)

        if len(attention_mask) != seq_len:
            raise ValueError(
                f"[{self.split_name}] attention_mask 길이가 input_ids와 다릅니다. "
                f"idx={idx}, len(input_ids)={seq_len}, len(attention_mask)={len(attention_mask)}"
            )

        if token_type_ids is not None and len(token_type_ids) != seq_len:
            raise ValueError(
                f"[{self.split_name}] token_type_ids 길이가 input_ids와 다릅니다. "
                f"idx={idx}, len(input_ids)={seq_len}, len(token_type_ids)={len(token_type_ids)}"
            )

        labels = torch.zeros((self.ent_type_size, seq_len, seq_len), dtype=torch.float32)

        for ent in entities:
            start = ent["start"]
            end = ent["end"]
            label = ent["label"]

            if label not in self.label2id:
                continue
            if not (0 <= start < seq_len and 0 <= end < seq_len):
                continue
            if end < start:
                continue

            labels[self.label2id[label], start, end] = 1.0

        item = {
            "text": text,
            "input_ids": torch.tensor(input_ids, dtype=torch.long),
            "attention_mask": torch.tensor(attention_mask, dtype=torch.long),
            "labels": labels,
            "entities": entities,
            "split": self.split_name,
        }

        if token_type_ids is not None:
            item["token_type_ids"] = torch.tensor(token_type_ids, dtype=torch.long)
        else:
            item["token_type_ids"] = None

        return item


# =========================================================
# 9. Collate
# =========================================================
def collate_fn(features):
    batch = {
        "texts": [f["text"] for f in features],
        "input_ids": torch.stack([f["input_ids"] for f in features], dim=0),
        "attention_mask": torch.stack([f["attention_mask"] for f in features], dim=0),
        "labels": torch.stack([f["labels"] for f in features], dim=0),
        "entities": [f["entities"] for f in features],
        "splits": [f["split"] for f in features],
    }

    token_type_ids_list = [f["token_type_ids"] for f in features]
    if all(x is not None for x in token_type_ids_list):
        batch["token_type_ids"] = torch.stack(token_type_ids_list, dim=0)
    else:
        batch["token_type_ids"] = None

    return batch


# =========================================================
# 10. 빠른 span 추출
# =========================================================
def extract_gold_entities_fast(labels: torch.Tensor, id2label: Dict[int, str]) -> Set[Tuple[str, int, int]]:
    indices = torch.nonzero(labels > 0, as_tuple=False)
    return {(id2label[int(c)], int(s), int(e)) for c, s, e in indices}


def extract_pred_entities_fast(logits: torch.Tensor, id2label: Dict[int, str], threshold: float = 0.0) -> Set[Tuple[str, int, int]]:
    indices = torch.nonzero(logits > threshold, as_tuple=False)
    return {(id2label[int(c)], int(s), int(e)) for c, s, e in indices}


# =========================================================
# 11. Eval
# =========================================================
@torch.no_grad()
def compute_f1_fast(model, dataloader, device, id2label, threshold=0.0, use_amp=True):
    model.eval()
    tp, fp, fn = 0, 0, 0

    amp_dtype = torch.float16 if device.startswith("cuda") else torch.float32

    for batch in dataloader:
        input_ids = batch["input_ids"].to(device, non_blocking=True)
        attention_mask = batch["attention_mask"].to(device, non_blocking=True)
        labels = batch["labels"].to(device, non_blocking=True)

        token_type_ids = batch["token_type_ids"]
        if token_type_ids is not None:
            token_type_ids = token_type_ids.to(device, non_blocking=True)

        with torch.autocast(device_type="cuda", dtype=amp_dtype, enabled=(use_amp and device.startswith("cuda"))):
            outputs = model(
                input_ids=input_ids,
                attention_mask=attention_mask,
                token_type_ids=token_type_ids
            )
            logits = outputs["logits"]

        logits = logits.float().cpu()
        labels = labels.cpu()

        for b in range(input_ids.size(0)):
            gold = extract_gold_entities_fast(labels[b], id2label)
            pred = extract_pred_entities_fast(logits[b], id2label, threshold)

            tp += len(gold & pred)
            fp += len(pred - gold)
            fn += len(gold - pred)

    precision = tp / (tp + fp + 1e-12)
    recall = tp / (tp + fn + 1e-12)
    f1 = 2 * precision * recall / (precision + recall + 1e-12)
    return precision, recall, f1


# =========================================================
# 12. Decode
# =========================================================
def decode_entities_from_logits_fast(logits: torch.Tensor, id2label: Dict[int, str], threshold: float = 0.0):
    """
    logits: (C, L, L)
    """
    indices = torch.nonzero(logits > threshold, as_tuple=False)
    if indices.numel() == 0:
        return []

    scores = logits[indices[:, 0], indices[:, 1], indices[:, 2]]

    entities = []
    for idx, score in zip(indices, scores):
        c, s, e = idx.tolist()
        entities.append({
            "label": id2label[c],
            "start": s,
            "end": e,
            "score": round(float(score.item()), 4)
        })

    entities.sort(key=lambda x: x["score"], reverse=True)
    return entities


# =========================================================
# 13. BIO 변환
# =========================================================
def convert_entities_to_bio(seq_len: int, entities: List[Dict]) -> List[str]:
    """
    span entity -> BIO tag
    entities: [{"label": "PER", "start": 1, "end": 3, "score": 0.95}, ...]
    """
    bio_tags = ["O"] * seq_len

    # score 높은 span부터 우선 반영
    sorted_entities = sorted(entities, key=lambda x: x.get("score", 0.0), reverse=True)
    occupied = [False] * seq_len

    for ent in sorted_entities:
        start = ent["start"]
        end = ent["end"]
        label = ent["label"]

        if not (0 <= start < seq_len and 0 <= end < seq_len):
            continue
        if end < start:
            continue

        # 이미 다른 엔티티가 차지한 구간이면 skip
        if any(occupied[i] for i in range(start, end + 1)):
            continue

        bio_tags[start] = f"B-{label}"
        occupied[start] = True

        for i in range(start + 1, end + 1):
            bio_tags[i] = f"I-{label}"
            occupied[i] = True

    return bio_tags


def convert_gold_entities_to_bio(seq_len: int, gold_entities: List[Dict]) -> List[str]:
    """
    gold entity -> BIO tag
    gold entity는 score가 없을 수 있으므로 별도 처리
    """
    bio_tags = ["O"] * seq_len

    for ent in gold_entities:
        start = ent["start"]
        end = ent["end"]
        label = ent["label"]

        if not (0 <= start < seq_len and 0 <= end < seq_len):
            continue
        if end < start:
            continue

        bio_tags[start] = f"B-{label}"
        for i in range(start + 1, end + 1):
            bio_tags[i] = f"I-{label}"

    return bio_tags


# =========================================================
# 14. JSON 출력 구성
# =========================================================
def build_prediction_output(sample: Dict, pred_entities: List[Dict]) -> Dict:
    seq_len = len(sample["input_ids"])

    pred_bio_tags = convert_entities_to_bio(seq_len, pred_entities)
    gold_bio_tags = convert_gold_entities_to_bio(seq_len, sample.get("entities", []))

    return {
        "text": sample["text"],
        "tokens": sample["input_ids"],  # 토큰 단위 동일하게 유지
        "gold_entities": sample.get("entities", []),
        "gold_bio_tags": gold_bio_tags,
        "raw_predictions": pred_entities,
        "pred_bio_tags": pred_bio_tags,
        "confidence_scores": [
            {
                "label": ent["label"],
                "start": ent["start"],
                "end": ent["end"],
                "score": ent["score"]
            }
            for ent in pred_entities
        ]
    }


# =========================================================
# 15. DataLoader 생성
# =========================================================
def build_dataloaders(cfg: Config):
    train_data = load_jsonl_file(cfg.train_json_path)
    valid_data = load_jsonl_file(cfg.valid_json_path)

    print(f"[INFO] train samples: {len(train_data)}")
    print(f"[INFO] valid samples: {len(valid_data)}")

    label2id, id2label = build_label_maps(train_data, valid_data)
    print(f"[INFO] label2id: {label2id}")

    train_dataset = LocalJsonlNERDataset(
        data=train_data,
        label2id=label2id,
        split_name="train"
    )
    valid_dataset = LocalJsonlNERDataset(
        data=valid_data,
        label2id=label2id,
        split_name="valid"
    )

    common_loader_kwargs = {
        "batch_size": cfg.batch_size,
        "collate_fn": collate_fn,
        "num_workers": cfg.num_workers,
        "pin_memory": torch.cuda.is_available(),
        "persistent_workers": cfg.num_workers > 0,
    }

    train_loader = DataLoader(
        train_dataset,
        shuffle=True,
        **common_loader_kwargs
    )
    valid_loader = DataLoader(
        valid_dataset,
        shuffle=False,
        **common_loader_kwargs
    )

    return label2id, id2label, train_loader, valid_loader


# =========================================================
# 16. Train
# =========================================================
def train():
    cfg = Config()

    label2id, id2label, train_loader, valid_loader = build_dataloaders(cfg)

    model = BertGlobalPointerForNER(
        pretrained_model_name=cfg.pretrained_model_name,
        ent_type_size=len(label2id),
        inner_dim=cfg.inner_dim,
        max_seq_len=512
    ).to(cfg.device)

    optimizer = AdamW(model.parameters(), lr=cfg.lr)
    scaler = torch.cuda.amp.GradScaler(enabled=(cfg.use_amp and cfg.device.startswith("cuda")))

    amp_dtype = torch.float16 if cfg.device.startswith("cuda") else torch.float32

    for epoch in range(cfg.epochs):
        model.train()
        total_loss = 0.0

        for step, batch in enumerate(train_loader):
            input_ids = batch["input_ids"].to(cfg.device, non_blocking=True)
            attention_mask = batch["attention_mask"].to(cfg.device, non_blocking=True)
            labels = batch["labels"].to(cfg.device, non_blocking=True)

            token_type_ids = batch["token_type_ids"]
            if token_type_ids is not None:
                token_type_ids = token_type_ids.to(cfg.device, non_blocking=True)

            optimizer.zero_grad(set_to_none=True)

            with torch.autocast(
                device_type="cuda",
                dtype=amp_dtype,
                enabled=(cfg.use_amp and cfg.device.startswith("cuda"))
            ):
                outputs = model(
                    input_ids=input_ids,
                    attention_mask=attention_mask,
                    token_type_ids=token_type_ids,
                    labels=labels
                )
                loss = outputs["loss"]

            scaler.scale(loss).backward()
            scaler.unscale_(optimizer)
            torch.nn.utils.clip_grad_norm_(model.parameters(), cfg.max_grad_norm)
            scaler.step(optimizer)
            scaler.update()

            total_loss += loss.item()

        avg_train_loss = total_loss / max(len(train_loader), 1)

        val_precision, val_recall, val_f1 = compute_f1_fast(
            model=model,
            dataloader=valid_loader,
            device=cfg.device,
            id2label=id2label,
            threshold=cfg.threshold,
            use_amp=cfg.use_amp
        )

        print(
            f"[Epoch {epoch+1}/{cfg.epochs}] "
            f"train_loss={avg_train_loss:.4f} "
            f"valid_precision={val_precision:.4f} "
            f"valid_recall={val_recall:.4f} "
            f"valid_f1={val_f1:.4f}"
        )

    return model, cfg, id2label


# =========================================================
# 17. Predict
# =========================================================
@torch.no_grad()
def predict_from_sample(model, cfg, id2label, sample: Dict, threshold: float = 0.0):
    model.eval()

    input_ids = torch.tensor(sample["input_ids"], dtype=torch.long).unsqueeze(0).to(cfg.device)
    attention_mask = torch.tensor(sample["attention_mask"], dtype=torch.long).unsqueeze(0).to(cfg.device)

    token_type_ids = sample.get("token_type_ids", None)
    if token_type_ids is not None:
        token_type_ids = torch.tensor(token_type_ids, dtype=torch.long).unsqueeze(0).to(cfg.device)

    amp_dtype = torch.float16 if cfg.device.startswith("cuda") else torch.float32

    with torch.autocast(
        device_type="cuda",
        dtype=amp_dtype,
        enabled=(cfg.use_amp and cfg.device.startswith("cuda"))
    ):
        outputs = model(
            input_ids=input_ids,
            attention_mask=attention_mask,
            token_type_ids=token_type_ids
        )
        logits = outputs["logits"].squeeze(0).float().cpu()

    pred_entities = decode_entities_from_logits_fast(logits, id2label, threshold=threshold)
    return pred_entities


# =========================================================
# 18. 전체 valid set 예측 저장
# =========================================================
@torch.no_grad()
def predict_and_save_all_valid(model, cfg, id2label, output_path: str = "/content/valid_predictions_bio.jsonl"):
    valid_samples = load_jsonl_file(cfg.valid_json_path)

    with open(output_path, "w", encoding="utf-8") as f:
        for sample in valid_samples:
            pred_entities = predict_from_sample(model, cfg, id2label, sample, threshold=cfg.threshold)
            result = build_prediction_output(sample, pred_entities)
            f.write(json.dumps(result, ensure_ascii=False) + "\n")

    print(f"[INFO] 예측 결과 저장 완료: {output_path}")


# =========================================================
# 19. 실행
# =========================================================
if __name__ == "__main__":
    model, cfg, id2label = train()

    valid_samples = load_jsonl_file(cfg.valid_json_path)
    test_sample = valid_samples[0]

    preds = predict_from_sample(
        model=model,
        cfg=cfg,
        id2label=id2label,
        sample=test_sample,
        threshold=cfg.threshold
    )

    output = build_prediction_output(test_sample, preds)

    print("\n[TEXT]")
    print(test_sample["text"])

    print("\n[GOLD ENTITIES]")
    for ent in test_sample.get("entities", []):
        print(ent)

    print("\n[GOLD BIO TAGS]")
    print(output["gold_bio_tags"])

    print("\n[PRED ENTITIES / RAW PREDICTIONS]")
    for ent in output["raw_predictions"][:20]:
        print(ent)

    print("\n[PRED BIO TAGS]")
    print(output["pred_bio_tags"])

    #print("\n[FINAL JSON OUTPUT]")
    #print(json.dumps(output, ensure_ascii=False, indent=2))

    # 전체 valid set 저장
    predict_and_save_all_valid(
        model=model,
        cfg=cfg,
        id2label=id2label,
        output_path="/content/valid_predictions_bio.jsonl"
    )