# -*- coding: utf-8 -*-
"""globalpointer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gQ-I_xW_o-SlxgY6SNGXBTNSV4Fir8Zx
"""

# -*- coding: utf-8 -*-
"""
GlobalPointer NER with BIO tag output
- span-based GlobalPointer 학습
- 예측 결과를 BIO 태그로 변환
- raw prediction / confidence score / JSON 출력 지원
"""

import os
import json
import math
from dataclasses import dataclass
from typing import Dict, List, Tuple, Optional, Set

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from transformers import AutoModel
from torch.optim import AdamW


# =========================================================
# 0. CUDA 성능 옵션
#    - GPU 사용 시 matmul / cudnn 최적화를 활성화
#    - Tensor Core 활용 가능 시 학습 속도 향상에 도움
#
#    torch.backends.cuda.matmul.allow_tf32
#    : 행렬 곱셈(MatMul) 연산에서 TF32(TensorFloat32) 데이터 형식을 허용할지 여부를 설정
#    torch.backends.cudnn.allow_tf32
#    : TF32(TensorFloat-32) 데이터 포맷을 허용할지 여부를 설정
#    torch.backends.cudnn.benchmark
#    : cuDNN 라이브러리의 컨볼루션(Convolution) 연산 알고리즘을 자동으로 최적화
# =========================================================
if torch.cuda.is_available():
    torch.backends.cuda.matmul.allow_tf32 = True
    torch.backends.cudnn.allow_tf32 = True
    torch.backends.cudnn.benchmark = True


# =========================================================
# 1. Config
#    모델/데이터/학습 관련 설정을 관리하는 클래스
# =========================================================
@dataclass
class Config:
    pretrained_model_name: str = "klue/bert-base" # 사전학습 모델 이름

    train_json_path: str = "/content/klue_ner_globalpointer_train.jsonl" # 학습 데이터 경로
    valid_json_path: str = "/content/klue_ner_globalpointer_valid.jsonl" # 검증 데이터 경로

    batch_size: int = 16 # 한 번에 학습할 배치 크기
    lr: float = 2e-5 # 학습률
    epochs: int = 5 # 전체 학습 epoch 수
    inner_dim: int = 64 # GlobalPointer 내부 차원
    threshold: float = 0.0 # 예측 span 추출 시 score threshold

    num_workers: int = 4 # DataLoader에서 데이터를 병렬로 읽어올 worker 수
    max_grad_norm: float = 1.0 # 역전파 시 gradient clipping에 사용할 최대 norm 값
    use_amp: bool = True # AMP(Automatic Mixed Precision) 사용 여부

    device: str = "cuda" if torch.cuda.is_available() else "cpu" # GPU 사용 가능 시 cuda, 아니면 cpu


# =========================================================
# 2. JSON / JSONL 로드
#    Args:
#        json_path (str): json 또는 jsonl 파일 경로
#
#    Returns:
#        data: List[Dict]
#    
#    Raises:
#        FileNotFoundError: 파일을 찾을 수 없습니다.
#        ValueError: 파일이 비어 있습니다.
#                    JSON은 리스트 형태여야 합니다.
#        JSONDecodeError: JSON 파싱 실패
# =========================================================
def load_jsonl_file(json_path: str) -> List[Dict]:
    if not os.path.exists(json_path):
        raise FileNotFoundError(f"파일을 찾을 수 없습니다: {json_path}")

    with open(json_path, "r", encoding="utf-8") as f:
        content = f.read().strip()

    if not content:
        raise ValueError(f"파일이 비어 있습니다: {json_path}")

    if content.startswith("["):
        try:
            data = json.loads(content)
            if not isinstance(data, list):
                raise ValueError("JSON은 리스트 형태여야 합니다.")
            return data
        except json.JSONDecodeError as e:
            raise ValueError(f"JSON 파싱 실패: {e}")

    data = []
    for line_num, line in enumerate(content.splitlines(), start=1):
        line = line.strip()
        if not line:
            continue
        try:
            data.append(json.loads(line))
        except json.JSONDecodeError as e:
            raise ValueError(f"{json_path} 파일의 {line_num}번째 줄 파싱 실패: {e}")

    return data


# =========================================================
# 3. label map 생성
#    Args:
#        train_data (List[Dict]): train 데이터
#        valid_data (List[Dict]): valid 데이터
#
#    Returns:
#        label2id (Dict[str, int]): 라벨명을 정수 id로 매핑한 딕셔너리
#        id2label (Dict[int, str]): 정수 id를 라벨명으로 매핑한 딕셔너리
# =========================================================
def build_label_maps(train_data: List[Dict], valid_data: List[Dict]) -> Tuple[Dict[str, int], Dict[int, str]]:
    entity_types = set()

    for dataset in [train_data, valid_data]:
        for sample in dataset:
            for ent in sample.get("entities", []):
                entity_types.add(ent["label"])

    entity_types = sorted(entity_types)
    label2id = {label: idx for idx, label in enumerate(entity_types)}
    id2label = {idx: label for label, idx in label2id.items()}
    return label2id, id2label


# =========================================================
# 4. Multi-label Categorical Crossentropy Loss
#    Args:
#        y_pred (torch.Tensor): 예측 logits, shape = (B, C, L, L)
#        y_true (torch.Tensor): 정답 label tensor, shape = (B, C, L, L)
#
#    Returns:
#        loss (torch.Tensor): 평균 loss
# =========================================================
def multilabel_categorical_crossentropy(y_pred: torch.Tensor, y_true: torch.Tensor) -> torch.Tensor:
    """
    y_pred, y_true: (batch, ent_type_size, seq_len, seq_len)
    """
    y_pred = (1 - 2 * y_true) * y_pred
    y_pred_neg = y_pred - y_true * 1e12
    y_pred_pos = y_pred - (1 - y_true) * 1e12

    zeros = torch.zeros_like(y_pred[..., :1])
    y_pred_neg = torch.cat([y_pred_neg, zeros], dim=-1)
    y_pred_pos = torch.cat([y_pred_pos, zeros], dim=-1)

    neg_loss = torch.logsumexp(y_pred_neg, dim=-1)
    pos_loss = torch.logsumexp(y_pred_pos, dim=-1)

    return (neg_loss + pos_loss).mean()


# =========================================================
# 5. RoPE positional embedding 캐시 클래스
#    Args:
#        max_seq_len (int): 최대 시퀀스 길이
#        inner_dim (int): RoPE 적용 차원
#
#    Attributes:
#        pos_emb (torch.Tensor): 미리 계산해둔 positional embedding
# =========================================================
class RoPEPositionEncoding(nn.Module):
    def __init__(self, max_seq_len: int, inner_dim: int):
        super().__init__()
        self.max_seq_len = max_seq_len
        self.inner_dim = inner_dim

        position_ids = torch.arange(0, max_seq_len, dtype=torch.float).unsqueeze(-1)
        indices = torch.arange(0, inner_dim // 2, dtype=torch.float)
        indices = torch.pow(10000, -2 * indices / inner_dim)

        embeddings = position_ids * indices
        sin_embeddings = torch.sin(embeddings)
        cos_embeddings = torch.cos(embeddings)

        pos_emb = torch.stack([sin_embeddings, cos_embeddings], dim=-1).reshape(max_seq_len, inner_dim)
        self.register_buffer("pos_emb", pos_emb, persistent=False)

    # =========================================================
    # 5-1. 캐시된 positional embedding 반환
    #    Args:
    #        seq_len (int): 현재 입력 시퀀스 길이
    #        batch_size (int): 현재 배치 크기
    #
    #    Returns:
    #        pos_emb (torch.Tensor): shape = (B, L, D)
    # =========================================================
    def forward(self, seq_len: int, batch_size: int) -> torch.Tensor:
        return self.pos_emb[:seq_len].unsqueeze(0).expand(batch_size, -1, -1)

# =========================================================
# 6. RoPE 적용 함수
#    Args:
#        x (torch.Tensor): 입력 텐서, shape = (B, L, C, D)
#        pos_emb (torch.Tensor): positional embedding, shape = (B, L, D)
#
#    Returns:
#        rotated_x (torch.Tensor): RoPE가 적용된 텐서
# =========================================================
def apply_rope(x: torch.Tensor, pos_emb: torch.Tensor) -> torch.Tensor:
    """
    x: (batch, seq_len, ent_type_size, inner_dim)
    pos_emb: (batch, seq_len, inner_dim)
    """
    cos_pos = pos_emb[..., 1::2].repeat_interleave(2, dim=-1)
    sin_pos = pos_emb[..., ::2].repeat_interleave(2, dim=-1)

    x2 = torch.stack([-x[..., 1::2], x[..., ::2]], dim=-1).reshape_as(x)
    return x * cos_pos.unsqueeze(2) + x2 * sin_pos.unsqueeze(2)


# =========================================================
# 7. GlobalPointer Head
#    Args:
#        hidden_size (int): encoder hidden size
#        ent_type_size (int): 엔티티 타입 개수
#        inner_dim (int): GlobalPointer 내부 차원
#        max_seq_len (int): 최대 시퀀스 길이
#        use_rope (bool): RoPE 사용 여부
# =========================================================
class GlobalPointer(nn.Module):
    def __init__(self, hidden_size: int, ent_type_size: int, inner_dim: int, max_seq_len: int = 512, use_rope: bool = True):
        super().__init__()
        self.ent_type_size = ent_type_size
        self.inner_dim = inner_dim
        self.use_rope = use_rope
        self.dense = nn.Linear(hidden_size, ent_type_size * inner_dim * 2)

        if use_rope:
            self.rope = RoPEPositionEncoding(max_seq_len=max_seq_len, inner_dim=inner_dim)

    # =========================================================
    # 7-1. GlobalPointer forward
    #    Args:
    #        last_hidden_state (torch.Tensor): encoder 출력, shape = (B, L, H)
    #        attention_mask (torch.Tensor): attention mask, shape = (B, L)
    #
    #    Returns:
    #        logits (torch.Tensor): span score, shape = (B, C, L, L)
    # =========================================================
    def forward(self, last_hidden_state: torch.Tensor, attention_mask: torch.Tensor) -> torch.Tensor:
        batch_size, seq_len, _ = last_hidden_state.size()

        outputs = self.dense(last_hidden_state)
        outputs = outputs.view(batch_size, seq_len, self.ent_type_size, self.inner_dim * 2)
        qw, kw = outputs[..., :self.inner_dim], outputs[..., self.inner_dim:]

        if self.use_rope:
            pos_emb = self.rope(seq_len=seq_len, batch_size=batch_size)
            qw = apply_rope(qw, pos_emb)
            kw = apply_rope(kw, pos_emb)

        logits = torch.einsum("bmhd,bnhd->bhmn", qw, kw)
        logits = logits / math.sqrt(self.inner_dim)

        mask1 = attention_mask.unsqueeze(1).unsqueeze(3)
        mask2 = attention_mask.unsqueeze(1).unsqueeze(2)
        pad_mask = mask1 * mask2
        logits = logits * pad_mask - (1 - pad_mask) * 1e12

        tril_mask = torch.tril(
            torch.ones(seq_len, seq_len, device=logits.device, dtype=logits.dtype),
            diagonal=-1
        )
        logits = logits - tril_mask.unsqueeze(0).unsqueeze(0) * 1e12

        return logits


# =========================================================
# 8. Encoder(Bert) + GlobalPointer 모델
#    Args:
#        pretrained_model_name (str): 사용할 사전학습 모델 이름
#        ent_type_size (int): 엔티티 타입 개수
#        inner_dim (int): GlobalPointer 내부 차원
#        max_seq_len (int): 최대 시퀀스 길이
# =========================================================
class BertGlobalPointerForNER(nn.Module):
    def __init__(self, pretrained_model_name: str, ent_type_size: int, inner_dim: int, max_seq_len: int = 512):
        super().__init__()
        self.encoder = AutoModel.from_pretrained(pretrained_model_name)
        hidden_size = self.encoder.config.hidden_size

        self.global_pointer = GlobalPointer(
            hidden_size=hidden_size,
            ent_type_size=ent_type_size,
            inner_dim=inner_dim,
            max_seq_len=max_seq_len,
            use_rope=True
        )

    # =========================================================
    # 8-1. 모델 forward
    #    Args:
    #        input_ids (torch.Tensor): 입력 토큰 id
    #        attention_mask (torch.Tensor): attention mask
    #        token_type_ids (torch.Tensor | None): token type ids
    #        labels (torch.Tensor | None): 정답 label tensor
    #
    #    Returns:
    #        result (Dict): logits, labels가 있으면 loss 포함
    # =========================================================
    def forward(self, input_ids, attention_mask, token_type_ids=None, labels=None):
        encoder_kwargs = {
            "input_ids": input_ids,
            "attention_mask": attention_mask,
        }

        if token_type_ids is not None:
            try:
                outputs = self.encoder(
                    input_ids=input_ids,
                    attention_mask=attention_mask,
                    token_type_ids=token_type_ids
                )
            except TypeError:
                outputs = self.encoder(**encoder_kwargs)
        else:
            outputs = self.encoder(**encoder_kwargs)

        last_hidden_state = outputs.last_hidden_state
        logits = self.global_pointer(last_hidden_state, attention_mask)

        result = {"logits": logits}
        if labels is not None:
            result["loss"] = multilabel_categorical_crossentropy(logits, labels)
        return result


# =========================================================
# 9. Local JSON/JSONL NER Dataset
#    Args:
#        data (List[Dict]): 데이터 샘플 리스트
#        label2id (Dict[str, int]): 라벨-아이디 매핑
#        split_name (str): 데이터 구분(train/valid/test)
# =========================================================
class LocalJsonlNERDataset(Dataset):
    def __init__(
        self,
        data: List[Dict],
        label2id: Dict[str, int],
        split_name: str
    ):
        self.data = data
        self.label2id = label2id
        self.ent_type_size = len(label2id)
        self.split_name = split_name

    # =========================================================
    # 9-1. 데이터셋 길이 반환
    #    Returns:
    #        length (int): 데이터셋 샘플 수
    # =========================================================
    def __len__(self):
        return len(self.data)

    # =========================================================
    # 9-2. 단일 샘플 반환
    #    Args:
    #        idx (int): 샘플 인덱스
    #
    #    Returns:
    #        item (Dict): 학습에 사용할 텐서 및 메타데이터
    #
    #    Raises:
    #        ValueError: attention_mask 길이가 input_ids와 다릅니다.
    #                    token_type_ids 길이가 input_ids와 다릅니다.
    # 
    # =========================================================
    def __getitem__(self, idx):
        sample = self.data[idx]

        text = sample["text"]
        input_ids = sample["input_ids"]
        attention_mask = sample["attention_mask"]
        token_type_ids = sample.get("token_type_ids", None)
        entities = sample.get("entities", [])

        seq_len = len(input_ids)

        if len(attention_mask) != seq_len:
            raise ValueError(
                f"[{self.split_name}] attention_mask 길이가 input_ids와 다릅니다. "
                f"idx={idx}, len(input_ids)={seq_len}, len(attention_mask)={len(attention_mask)}"
            )

        if token_type_ids is not None and len(token_type_ids) != seq_len:
            raise ValueError(
                f"[{self.split_name}] token_type_ids 길이가 input_ids와 다릅니다. "
                f"idx={idx}, len(input_ids)={seq_len}, len(token_type_ids)={len(token_type_ids)}"
            )

        labels = torch.zeros((self.ent_type_size, seq_len, seq_len), dtype=torch.float32)

        for ent in entities:
            start = ent["start"]
            end = ent["end"]
            label = ent["label"]

            if label not in self.label2id:
                continue
            if not (0 <= start < seq_len and 0 <= end < seq_len):
                continue
            if end < start:
                continue

            labels[self.label2id[label], start, end] = 1.0

        item = {
            "text": text,
            "input_ids": torch.tensor(input_ids, dtype=torch.long),
            "attention_mask": torch.tensor(attention_mask, dtype=torch.long),
            "labels": labels,
            "entities": entities,
            "split": self.split_name,
        }

        if token_type_ids is not None:
            item["token_type_ids"] = torch.tensor(token_type_ids, dtype=torch.long)
        else:
            item["token_type_ids"] = None

        return item


# =========================================================
# 10. Collate 함수
#    Args:
#        features (List[Dict]): Dataset에서 꺼낸 샘플 리스트
#
#    Returns:
#        batch (Dict): 배치 단위 텐서 묶음
# =========================================================
def collate_fn(features):
    batch = {
        "texts": [f["text"] for f in features],
        "input_ids": torch.stack([f["input_ids"] for f in features], dim=0),
        "attention_mask": torch.stack([f["attention_mask"] for f in features], dim=0),
        "labels": torch.stack([f["labels"] for f in features], dim=0),
        "entities": [f["entities"] for f in features],
        "splits": [f["split"] for f in features],
    }

    token_type_ids_list = [f["token_type_ids"] for f in features]
    if all(x is not None for x in token_type_ids_list):
        batch["token_type_ids"] = torch.stack(token_type_ids_list, dim=0)
    else:
        batch["token_type_ids"] = None

    return batch


# =========================================================
# 11. gold entity 추출
#    Args:
#        labels (torch.Tensor): 정답 label tensor, shape = (C, L, L)
#        id2label (Dict[int, str]): id -> label 매핑
#
#    Returns:
#        results (Set[Tuple[str, int, int]]): 정답 엔티티 집합
# =========================================================
def extract_gold_entities_fast(labels: torch.Tensor, id2label: Dict[int, str]) -> Set[Tuple[str, int, int]]:
    indices = torch.nonzero(labels > 0, as_tuple=False)
    return {(id2label[int(c)], int(s), int(e)) for c, s, e in indices}

# =========================================================
# 12. prediction entity 추출
#    Args:
#        logits (torch.Tensor): 예측 logits, shape = (C, L, L)
#        id2label (Dict[int, str]): id -> label 매핑
#        threshold (float): score threshold
#
#    Returns:
#        results (Set[Tuple[str, int, int]]): 예측 엔티티 집합
# =========================================================
def extract_pred_entities_fast(logits: torch.Tensor, id2label: Dict[int, str], threshold: float = 0.0) -> Set[Tuple[str, int, int]]:
    indices = torch.nonzero(logits > threshold, as_tuple=False)
    return {(id2label[int(c)], int(s), int(e)) for c, s, e in indices}

# =========================================================
# 13. F1 계산
#    Args:
#        model: 학습된 모델
#        dataloader: 검증 데이터 로더
#        device (str): 실행 장치
#        id2label (Dict[int, str]): id -> label 매핑
#        threshold (float): score threshold
#        use_amp (bool): AMP 사용 여부
#
#    Returns:
#        precision (float): 정밀도
#        recall (float): 재현율
#        f1 (float): F1 score
# =========================================================
@torch.no_grad()
def compute_f1_fast(model, dataloader, device, id2label, threshold=0.0, use_amp=True):
    model.eval()
    tp, fp, fn = 0, 0, 0

    amp_dtype = torch.float16 if device.startswith("cuda") else torch.float32

    for batch in dataloader:
        input_ids = batch["input_ids"].to(device, non_blocking=True)
        attention_mask = batch["attention_mask"].to(device, non_blocking=True)
        labels = batch["labels"].to(device, non_blocking=True)

        token_type_ids = batch["token_type_ids"]
        if token_type_ids is not None:
            token_type_ids = token_type_ids.to(device, non_blocking=True)

        with torch.autocast(device_type="cuda", dtype=amp_dtype, enabled=(use_amp and device.startswith("cuda"))):
            outputs = model(
                input_ids=input_ids,
                attention_mask=attention_mask,
                token_type_ids=token_type_ids
            )
            logits = outputs["logits"]

        logits = logits.float().cpu()
        labels = labels.cpu()

        for b in range(input_ids.size(0)):
            gold = extract_gold_entities_fast(labels[b], id2label)
            pred = extract_pred_entities_fast(logits[b], id2label, threshold)

            tp += len(gold & pred)
            fp += len(pred - gold)
            fn += len(gold - pred)

    precision = tp / (tp + fp + 1e-12)
    recall = tp / (tp + fn + 1e-12)
    f1 = 2 * precision * recall / (precision + recall + 1e-12)
    return precision, recall, f1


# =========================================================
# 14. logits -> raw entity decode
#    Args:
#        logits (torch.Tensor): 예측 logits, shape = (C, L, L)
#        id2label (Dict[int, str]): id -> label 매핑
#        threshold (float): score threshold
#
#    Returns:
#        entities (List[Dict]): raw prediction 리스트
# =========================================================
def decode_entities_from_logits_fast(logits: torch.Tensor, id2label: Dict[int, str], threshold: float = 0.0):
    """
    logits: (C, L, L)
    """
    indices = torch.nonzero(logits > threshold, as_tuple=False)
    if indices.numel() == 0:
        return []

    scores = logits[indices[:, 0], indices[:, 1], indices[:, 2]]

    entities = []
    for idx, score in zip(indices, scores):
        c, s, e = idx.tolist()
        entities.append({
            "label": id2label[c],
            "start": s,
            "end": e,
            "score": round(float(score.item()), 4)
        })

    entities.sort(key=lambda x: x["score"], reverse=True)
    return entities


# =========================================================
# 15-1. 예측 엔티티를 BIO 태그로 변환
#    Args:
#        seq_len (int): 시퀀스 길이
#        entities (List[Dict]): 예측 엔티티 리스트
#            예: [{"label": "PER", "start": 1, "end": 3, "score": 0.95}, ...]
#
#    Returns:
#        bio_tags (List[str]): BIO 형식의 토큰 단위 태그 리스트
#
#    Notes:
#        - score가 높은 span부터 우선 반영합니다.
#        - 이미 다른 엔티티가 점유한 구간은 중복 반영하지 않습니다.
#        - 범위를 벗어나거나 end < start 인 span은 무시합니다.
# =========================================================
def convert_entities_to_bio(seq_len: int, entities: List[Dict]) -> List[str]:
    """
    span entity -> BIO tag
    entities: [{"label": "PER", "start": 1, "end": 3, "score": 0.95}, ...]
    """
    bio_tags = ["O"] * seq_len

    # score 높은 span부터 우선 반영
    sorted_entities = sorted(entities, key=lambda x: x.get("score", 0.0), reverse=True)
    occupied = [False] * seq_len

    for ent in sorted_entities:
        start = ent["start"]
        end = ent["end"]
        label = ent["label"]

        if not (0 <= start < seq_len and 0 <= end < seq_len):
            continue
        if end < start:
            continue

        # 이미 다른 엔티티가 차지한 구간이면 skip
        if any(occupied[i] for i in range(start, end + 1)):
            continue

        bio_tags[start] = f"B-{label}"
        occupied[start] = True

        for i in range(start + 1, end + 1):
            bio_tags[i] = f"I-{label}"
            occupied[i] = True

    return bio_tags

# =========================================================
# 15-2. 정답 엔티티를 BIO 태그로 변환
#    Args:
#        seq_len (int): 시퀀스 길이
#        gold_entities (List[Dict]): 정답 엔티티 리스트
#            예: [{"label": "PER", "start": 1, "end": 3}, ...]
#
#    Returns:
#        bio_tags (List[str]): 정답 기준 BIO 형식 태그 리스트
#
#    Notes:
#        - gold entity는 일반적으로 score가 없으므로 별도로 처리합니다.
#        - 범위를 벗어나거나 end < start 인 span은 무시합니다.
# =========================================================
def convert_gold_entities_to_bio(seq_len: int, gold_entities: List[Dict]) -> List[str]:
    """
    gold entity -> BIO tag
    gold entity는 score가 없을 수 있으므로 별도 처리
    """
    bio_tags = ["O"] * seq_len

    for ent in gold_entities:
        start = ent["start"]
        end = ent["end"]
        label = ent["label"]

        if not (0 <= start < seq_len and 0 <= end < seq_len):
            continue
        if end < start:
            continue

        bio_tags[start] = f"B-{label}"
        for i in range(start + 1, end + 1):
            bio_tags[i] = f"I-{label}"

    return bio_tags


# =========================================================
# 16. JSON 출력 구성
#    Args:
#        sample (Dict): 원본 샘플 데이터
#            예: {
#                "text": ...,
#                "input_ids": [...],
#                "entities": [...]
#            }
#        pred_entities (List[Dict]): 모델이 예측한 엔티티 리스트
#
#    Returns:
#        output (Dict): JSON 저장용 결과 딕셔너리
#
#    Notes:
#        - tokens는 입력의 토큰 단위를 그대로 유지하기 위해 input_ids를 사용합니다.
#        - gold_bio_tags는 정답 엔티티 기준 BIO 태그입니다.
#        - pred_bio_tags는 예측 엔티티 기준 BIO 태그입니다.
#        - confidence_scores는 raw prediction에서 label/start/end/score만 추출한 정보입니다.
# =========================================================
def build_prediction_output(sample: Dict, pred_entities: List[Dict]) -> Dict:
    seq_len = len(sample["input_ids"])

    pred_bio_tags = convert_entities_to_bio(seq_len, pred_entities)
    gold_bio_tags = convert_gold_entities_to_bio(seq_len, sample.get("entities", []))

    return {
        "text": sample["text"],
        "tokens": sample["input_ids"],  # 토큰 단위 동일하게 유지
        "gold_entities": sample.get("entities", []),
        "gold_bio_tags": gold_bio_tags,
        "raw_predictions": pred_entities,
        "pred_bio_tags": pred_bio_tags,
        "confidence_scores": [
            {
                "label": ent["label"],
                "start": ent["start"],
                "end": ent["end"],
                "score": ent["score"]
            }
            for ent in pred_entities
        ]
    }


# =========================================================
# 17. DataLoader 생성
#    Args:
#        cfg (Config): 전체 설정 객체
#
#    Returns:
#        label2id (Dict[str, int]): 라벨 -> id 매핑
#        id2label (Dict[int, str]): id -> 라벨 매핑
#        train_loader (DataLoader): 학습 데이터로더
#        valid_loader (DataLoader): 검증 데이터로더
# =========================================================
def build_dataloaders(cfg: Config):
    train_data = load_jsonl_file(cfg.train_json_path)
    valid_data = load_jsonl_file(cfg.valid_json_path)

    print(f"[INFO] train samples: {len(train_data)}")
    print(f"[INFO] valid samples: {len(valid_data)}")

    label2id, id2label = build_label_maps(train_data, valid_data)
    print(f"[INFO] label2id: {label2id}")
    # DT-날짜-0,LC-장소-1,OG-기관-2,PS-사람-3,QT-수량-4,TI-시간-5

    train_dataset = LocalJsonlNERDataset(
        data=train_data,
        label2id=label2id,
        split_name="train"
    )
    valid_dataset = LocalJsonlNERDataset(
        data=valid_data,
        label2id=label2id,
        split_name="valid"
    )

    common_loader_kwargs = {
        "batch_size": cfg.batch_size,
        "collate_fn": collate_fn,
        "num_workers": cfg.num_workers,
        "pin_memory": torch.cuda.is_available(),
        "persistent_workers": cfg.num_workers > 0,
    }

    train_loader = DataLoader(
        train_dataset,
        shuffle=True,
        **common_loader_kwargs
    )
    valid_loader = DataLoader(
        valid_dataset,
        shuffle=False,
        **common_loader_kwargs
    )

    return label2id, id2label, train_loader, valid_loader


# =========================================================
# 18. 학습 함수
#    Args:
#        없음
#
#    Returns:
#        model: 학습 완료된 모델
#        cfg (Config): 설정 객체
#        id2label (Dict[int, str]): id -> label 매핑
# =========================================================
def train():
    cfg = Config()

    label2id, id2label, train_loader, valid_loader = build_dataloaders(cfg)

    model = BertGlobalPointerForNER(
        pretrained_model_name=cfg.pretrained_model_name,
        ent_type_size=len(label2id),
        inner_dim=cfg.inner_dim,
        max_seq_len=512
    ).to(cfg.device)

    optimizer = AdamW(model.parameters(), lr=cfg.lr)
    scaler = torch.cuda.amp.GradScaler(enabled=(cfg.use_amp and cfg.device.startswith("cuda")))

    amp_dtype = torch.float16 if cfg.device.startswith("cuda") else torch.float32

    for epoch in range(cfg.epochs):
        model.train()
        total_loss = 0.0

        for step, batch in enumerate(train_loader):
            input_ids = batch["input_ids"].to(cfg.device, non_blocking=True)
            attention_mask = batch["attention_mask"].to(cfg.device, non_blocking=True)
            labels = batch["labels"].to(cfg.device, non_blocking=True)

            token_type_ids = batch["token_type_ids"]
            if token_type_ids is not None:
                token_type_ids = token_type_ids.to(cfg.device, non_blocking=True)

            optimizer.zero_grad(set_to_none=True)

            with torch.autocast(
                device_type="cuda",
                dtype=amp_dtype,
                enabled=(cfg.use_amp and cfg.device.startswith("cuda"))
            ):
                outputs = model(
                    input_ids=input_ids,
                    attention_mask=attention_mask,
                    token_type_ids=token_type_ids,
                    labels=labels
                )
                loss = outputs["loss"]

            scaler.scale(loss).backward()
            scaler.unscale_(optimizer)
            torch.nn.utils.clip_grad_norm_(model.parameters(), cfg.max_grad_norm)
            scaler.step(optimizer)
            scaler.update()

            total_loss += loss.item()

        avg_train_loss = total_loss / max(len(train_loader), 1)

        val_precision, val_recall, val_f1 = compute_f1_fast(
            model=model,
            dataloader=valid_loader,
            device=cfg.device,
            id2label=id2label,
            threshold=cfg.threshold,
            use_amp=cfg.use_amp
        )

        print(
            f"[Epoch {epoch+1}/{cfg.epochs}] "
            f"train_loss={avg_train_loss:.4f} "
            f"valid_precision={val_precision:.4f} "
            f"valid_recall={val_recall:.4f} "
            f"valid_f1={val_f1:.4f}"
        )

    return model, cfg, id2label


# =========================================================
# 19. 단일 샘플 예측
#    Args:
#        model: 학습된 모델
#        cfg (Config): 설정 객체
#        id2label (Dict[int, str]): id -> label 매핑
#        sample (Dict): 예측할 샘플
#        threshold (float): score threshold
#
#    Returns:
#        pred_entities (List[Dict]): 예측된 엔티티 리스트
# =========================================================
@torch.no_grad()
def predict_from_sample(model, cfg, id2label, sample: Dict, threshold: float = 0.0):
    model.eval()

    input_ids = torch.tensor(sample["input_ids"], dtype=torch.long).unsqueeze(0).to(cfg.device)
    attention_mask = torch.tensor(sample["attention_mask"], dtype=torch.long).unsqueeze(0).to(cfg.device)

    token_type_ids = sample.get("token_type_ids", None)
    if token_type_ids is not None:
        token_type_ids = torch.tensor(token_type_ids, dtype=torch.long).unsqueeze(0).to(cfg.device)

    amp_dtype = torch.float16 if cfg.device.startswith("cuda") else torch.float32

    with torch.autocast(
        device_type="cuda",
        dtype=amp_dtype,
        enabled=(cfg.use_amp and cfg.device.startswith("cuda"))
    ):
        outputs = model(
            input_ids=input_ids,
            attention_mask=attention_mask,
            token_type_ids=token_type_ids
        )
        logits = outputs["logits"].squeeze(0).float().cpu()

    pred_entities = decode_entities_from_logits_fast(logits, id2label, threshold=threshold)
    return pred_entities


# =========================================================
# 20. 테스트셋 전체 예측 후 JSON 저장
#    Args:
#        model: 학습된 모델
#        cfg (Config): 설정 객체
#        id2label (Dict[int, str]): id -> label 매핑
#        output_path: 저장 경로
#
#    Returns:
#        results (List[Dict]): 테스트셋 raw prediction 결과
# =========================================================
@torch.no_grad()
def predict_and_save_all_valid(model, cfg, id2label, output_path: str = "/content/valid_predictions_bio.jsonl"):
    valid_samples = load_jsonl_file(cfg.valid_json_path)

    with open(output_path, "w", encoding="utf-8") as f:
        for sample in valid_samples:
            pred_entities = predict_from_sample(model, cfg, id2label, sample, threshold=cfg.threshold)
            result = build_prediction_output(sample, pred_entities)
            f.write(json.dumps(result, ensure_ascii=False) + "\n")

    print(f"[INFO] 예측 결과 저장 완료: {output_path}")


# =========================================================
# 21. 메인 실행부
#    - 모델 학습
#    - valid 첫 샘플 예측 확인
#    - test 전체 예측 후 JSON 저장
# =========================================================
if __name__ == "__main__":
    model, cfg, id2label = train()

    valid_samples = load_jsonl_file(cfg.valid_json_path)
    test_sample = valid_samples[0]

    preds = predict_from_sample(
        model=model,
        cfg=cfg,
        id2label=id2label,
        sample=test_sample,
        threshold=cfg.threshold
    )

    output = build_prediction_output(test_sample, preds)

    print("\n[TEXT]")
    print(test_sample["text"])

    print("\n[GOLD ENTITIES]")
    for ent in test_sample.get("entities", []):
        print(ent)

    print("\n[GOLD BIO TAGS]")
    print(output["gold_bio_tags"])

    print("\n[PRED ENTITIES / RAW PREDICTIONS]")
    for ent in output["raw_predictions"][:20]:
        print(ent)

    print("\n[PRED BIO TAGS]")
    print(output["pred_bio_tags"])

    #print("\n[FINAL JSON OUTPUT]")
    #print(json.dumps(output, ensure_ascii=False, indent=2))

    # 전체 valid set 저장
    predict_and_save_all_valid(
        model=model,
        cfg=cfg,
        id2label=id2label,
        output_path="/content/valid_predictions_bio.jsonl"
    )