# -*- coding: utf-8 -*-
"""GLiNER1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uFgeBRG7q4q9bx6beAbOlewO9AL2AdFw
"""

# 1. 필요 라이브러리 설치 (코랩용)
!pip install -q datasets transformers

import torch
from datasets import load_dataset
from transformers import AutoTokenizer

# ==========================================
# 2. 초기 설정 (토크나이저 및 데이터셋 로드)
# ==========================================
print("데이터셋과 토크나이저를 로드합니다...")
# BERT로 변경 완료!
tokenizer = AutoTokenizer.from_pretrained("klue/bert-base")
dataset = load_dataset("klue", "ner")

# KLUE NER의 6가지 엔티티 타입 정의 (O 태그 제외)
ENTITY_TYPES = ["PS", "LC", "OG", "DT", "TI", "QT"]
entity2id = {ent: idx for idx, ent in enumerate(ENTITY_TYPES)}

# KLUE 원본 데이터셋의 라벨 이름 (0: O, 1: B-PS, 2: I-PS ...)
klue_id2label = dataset["train"].features["ner_tags"].feature.names

# ==========================================
# 3. 전처리 함수 정의
# ==========================================
def extract_spans(ner_tags):
    """BIO 태그 리스트를 [(단어 시작 인덱스, 단어 끝 인덱스, 엔티티 종류), ...] 형태로 변환"""
    spans = []
    current_span = None

    for i, tag_id in enumerate(ner_tags):
        tag_name = klue_id2label[tag_id]
        if tag_name == "O":
            if current_span:
                spans.append(current_span)
                current_span = None
        elif tag_name.startswith("B-"):
            if current_span:
                spans.append(current_span)
            current_span = [i, i, tag_name[2:]] # [시작, 끝, 라벨(PS, LC 등)]
        elif tag_name.startswith("I-"):
            if current_span and current_span[2] == tag_name[2:]:
                current_span[1] = i # 끝 인덱스 업데이트
            else:
                if current_span: spans.append(current_span)
                current_span = [i, i, tag_name[2:]]
    if current_span:
        spans.append(current_span)

    return spans

def preprocess_for_gliner(example, max_length=512):
    """단일 샘플을 GLiNER 모델 입력 형식에 맞게 변환"""
    words = example["tokens"]
    ner_tags = example["ner_tags"]

    # 1. 단어 단위 스팬(Span) 추출
    word_spans = extract_spans(ner_tags)

    # 2. Entity 프롬프트 토큰화
    ent_tokens = []
    for et in ENTITY_TYPES:
        ent_tokens.extend(tokenizer.tokenize(et) + [tokenizer.sep_token])

    # 3. 본문 Text 토큰화 및 단어 인덱스 추적
    text_tokens = []
    word_index_list = []
    word_to_subword_idx = [] # 원본 단어 인덱스 -> (서브워드 시작, 서브워드 끝)

    current_subword_idx = 0
    for i, word in enumerate(words):
        subwords = tokenizer.tokenize(word)
        if not subwords:
            subwords = [tokenizer.unk_token]

        text_tokens.extend(subwords)
        word_index_list.extend([i] * len(subwords))

        word_to_subword_idx.append((current_subword_idx, current_subword_idx + len(subwords) - 1))
        current_subword_idx += len(subwords)

    # [Truncation 처리] 최대 길이 초과 방지
    max_text_len = max_length - len(ent_tokens) - 2 # [CLS], [SEP] 공간 제외
    if len(text_tokens) > max_text_len:
        text_tokens = text_tokens[:max_text_len]
        word_index_list = word_index_list[:max_text_len]

    # 4. 전체 시퀀스 결합
    input_tokens = [tokenizer.cls_token] + ent_tokens + text_tokens + [tokenizer.sep_token]
    input_ids = tokenizer.convert_tokens_to_ids(input_tokens)

    seq_len = len(input_ids)
    attention_mask = [1] * seq_len
    ent_mask = [0] * seq_len
    text_mask = [0] * seq_len
    word_index = [-1] * seq_len

    # === [여기가 핵심 수정된 부분입니다!] ===
    # 각 엔티티의 "첫 번째 서브워드"에만 딱 1이 들어가도록 수정
    ent_start = 1
    current_idx = ent_start
    for et in ENTITY_TYPES:
        et_subwords = tokenizer.tokenize(et)
        ent_mask[current_idx] = 1 # 첫 글자에만 1 켜기!
        # 현재 엔티티 서브워드 길이 + [SEP] 1개만큼 점프
        current_idx += len(et_subwords) + 1
    # ==========================================

    text_start = ent_start + len(ent_tokens)
    for i in range(len(text_tokens)):
        global_idx = text_start + i
        text_mask[global_idx] = 1
        word_index[global_idx] = word_index_list[i]

    # 5. GLiNER 형식의 Span Labels 생성 (Text 영역 내부 기준)
    span_labels = []
    for start_word, end_word, label_str in word_spans:
        # Truncation 범위를 벗어난 엔티티는 제외
        if end_word >= len(word_to_subword_idx):
            continue

        subword_start = word_to_subword_idx[start_word][0]
        subword_end = word_to_subword_idx[end_word][1]

        if subword_end >= max_text_len:
            continue # 잘린 텍스트 밖의 라벨 무시

        label_id = entity2id[label_str]
        # (text_mask 기준 시작점, 끝점, 클래스 ID) 튜플 추가
        span_labels.append((subword_start, subword_end, label_id))

    return {
        "input_ids": input_ids,
        "attention_mask": attention_mask,
        "ent_mask": ent_mask,
        "text_mask": text_mask,
        "word_index": word_index,
        "span_labels": span_labels
    }

# ==========================================
# 4. 전체 데이터셋에 적용 (.map)
# ==========================================
print("데이터셋 전처리를 시작합니다 (약간의 시간이 소요될 수 있습니다)...")
processed_dataset = dataset.map(
    preprocess_for_gliner,
    remove_columns=dataset["train"].column_names # 기존 불필요한 컬럼 삭제
)

# 결과 확인
print("\n[전처리 완료! 첫 번째 샘플 확인]")
sample = processed_dataset["train"][0]

print(f"input_ids: {sample['input_ids'][:15]} ...")
print(f"attention_mask: {sample['attention_mask'][:15]} ...")
print(f"ent_mask: {sample['ent_mask'][:15]} ...")
print(f"text_mask: {sample['text_mask'][:30]} ...")
print(f"word_index: {sample['word_index'][:30]} ...")
print(f"span_labels: {sample['span_labels']}")


processed_dataset.save_to_disk("klue_ner_preprocessed")

processed_dataset["train"].to_json("train_gliner.jsonl")
processed_dataset["validation"].to_json("val_gliner.jsonl")