# -*- coding: utf-8 -*-
"""evaluate_generalization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n_ircip0Z8FBdg5zi4vzI35mDPp5sVh9
"""

!pip install pytorch-crf seqeval transformers

# -*- coding: utf-8 -*-
!pip install -q pytorch-crf seqeval transformers

import os
import json
import torch
import torch.nn as nn
import numpy as np

from tqdm import tqdm
from torchcrf import CRF
from transformers import AutoTokenizer, AutoModel
from seqeval.metrics import precision_score, recall_score, f1_score, classification_report
from seqeval.metrics.sequence_labeling import get_entities

# =========================================================
# 0. 기본 설정
# =========================================================
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("device:", device)

tokenizer = AutoTokenizer.from_pretrained("klue/bert-base")

# =========================================================
# 1. 6개 엔티티 설정
# =========================================================
ENTITY_TYPES = ["PS", "LC", "OG", "DT", "TI", "QT"]

label_list = []
for ent in ENTITY_TYPES:
    label_list.append(f"B-{ent}")
    label_list.append(f"I-{ent}")
label_list.append("O")

label2id = {label: i for i, label in enumerate(label_list)}
id2label = {i: label for label, i in label2id.items()}

NUM_CRF_CLASSES = len(label_list)  # 13
print("CRF num_classes =", NUM_CRF_CLASSES)

# =========================================================
# 2. valid 데이터의 15개 라벨 -> 6개 라벨만 남기는 함수
# =========================================================
def filter_bio_tags_to_target_entities(bio_tags, target_entities):
    keep_tags = set()
    for ent in target_entities:
        keep_tags.add(f"B-{ent}")
        keep_tags.add(f"I-{ent}")

    filtered = []
    for tag in bio_tags:
        if tag in keep_tags:
            filtered.append(tag)
        else:
            filtered.append("O")
    return filtered

# =========================================================
# 3. CRF 모델
# =========================================================
class BertCRF(nn.Module):
    def __init__(self, model_name, num_classes, dropout=0.1):
        super().__init__()
        self.bert = AutoModel.from_pretrained(model_name)
        hidden_size = self.bert.config.hidden_size
        self.dropout = nn.Dropout(dropout)
        self.position_wise_ff = nn.Linear(hidden_size, num_classes)
        self.crf = CRF(num_tags=num_classes, batch_first=True)

    def forward(self, input_ids, attention_mask=None, tags=None):
        outputs = self.bert(input_ids=input_ids, attention_mask=attention_mask)
        sequence_output = self.dropout(outputs.last_hidden_state)
        emissions = self.position_wise_ff(sequence_output)

        crf_mask = attention_mask.bool() if attention_mask is not None else torch.ones_like(input_ids, dtype=torch.bool)

        if tags is not None:
            log_likelihood = self.crf(emissions, tags, mask=crf_mask, reduction="mean")
            pred = self.crf.decode(emissions, mask=crf_mask)
            return -log_likelihood, pred
        else:
            pred = self.crf.decode(emissions, mask=crf_mask)
            return None, pred

# =========================================================
# 4. GLiNER 모델 구성
# =========================================================
class EncoderModule(nn.Module):
    def __init__(self, backbone_model: str):
        super().__init__()
        self.encoder = AutoModel.from_pretrained(backbone_model)
        self.hidden_size = self.encoder.config.hidden_size

    def forward(self, input_ids: torch.Tensor, attention_mask: torch.Tensor) -> torch.Tensor:
        outputs = self.encoder(input_ids=input_ids, attention_mask=attention_mask)
        return outputs.last_hidden_state

class WordTokenRepresentation(nn.Module):
    def __init__(self, pooling="mean"):
        super().__init__()
        assert pooling in ["mean", "first"]
        self.pooling = pooling

    def forward(self, hidden_states, text_mask, word_index):
        batch_word_embeddings = []
        word_lens = []

        B, L, H = hidden_states.shape

        for b in range(B):
            hs = hidden_states[b]
            tm = text_mask[b]
            wi = word_index[b]

            valid_pos = (tm == 1) & (wi >= 0)
            hs_valid = hs[valid_pos]
            wi_valid = wi[valid_pos]

            if wi_valid.numel() == 0:
                word_vecs = torch.zeros(1, H, device=hidden_states.device, dtype=hidden_states.dtype)
            else:
                max_word_idx = int(wi_valid.max().item())
                num_words = max_word_idx + 1

                tmp = []
                for word_id in range(num_words):
                    token_vecs = hs_valid[wi_valid == word_id]
                    if token_vecs.size(0) == 0:
                        word_vec = torch.zeros(H, device=hidden_states.device, dtype=hidden_states.dtype)
                    else:
                        if self.pooling == "mean":
                            word_vec = token_vecs.mean(dim=0)
                        else:
                            word_vec = token_vecs[0]
                    tmp.append(word_vec)

                word_vecs = torch.stack(tmp, dim=0)

            batch_word_embeddings.append(word_vecs)
            word_lens.append(word_vecs.size(0))

        max_len = max(word_lens)
        padded = []

        for x in batch_word_embeddings:
            pad_len = max_len - x.size(0)
            if pad_len > 0:
                pad = torch.zeros(pad_len, x.size(1), device=x.device, dtype=x.dtype)
                x = torch.cat([x, pad], dim=0)
            padded.append(x)

        padded_word_embeddings = torch.stack(padded, dim=0)
        word_lens = torch.tensor(word_lens, device=hidden_states.device, dtype=torch.long)

        return padded_word_embeddings, word_lens

class ENTTokenRepresentation(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, hidden_states, ent_mask):
        ent_vectors = []

        for hs, mask in zip(hidden_states, ent_mask):
            p_vector = hs[mask.bool()]
            ent_vectors.append(p_vector)

        max_ent = max(v.size(0) for v in ent_vectors)
        hidden_size = hidden_states.size(-1)

        padded_ent_vectors = []
        padded_ent_masks = []

        for v in ent_vectors:
            m = v.size(0)
            pad_len = max_ent - m

            if pad_len > 0:
                pad_tensor = torch.zeros(
                    pad_len,
                    hidden_size,
                    device=v.device,
                    dtype=v.dtype
                )
                v = torch.cat([v, pad_tensor], dim=0)

            valid_mask = torch.cat([
                torch.ones(m, device=v.device, dtype=torch.bool),
                torch.zeros(pad_len, device=v.device, dtype=torch.bool)
            ], dim=0)

            padded_ent_vectors.append(v)
            padded_ent_masks.append(valid_mask)

        ent_vectors = torch.stack(padded_ent_vectors, dim=0)
        ent_valid_mask = torch.stack(padded_ent_masks, dim=0)

        return ent_vectors, ent_valid_mask

class Linear(nn.Module):
    def __init__(self, input_x, output_y, bias=True):
        super().__init__()
        self.linear = nn.Linear(input_x, output_y, bias=bias)

    def forward(self, x):
        return self.linear(x)

class ReLU(nn.Module):
    def forward(self, x):
        return x * (x > 0)

class Sequential(nn.Module):
    def __init__(self, *layers):
        super().__init__()
        self.layers = nn.ModuleList(layers)

    def forward(self, x):
        for layer in self.layers:
            x = layer(x)
        return x

class EntityRepresentation(nn.Module):
    def __init__(self, d_model, d_ff):
        super().__init__()
        self.net = Sequential(
            Linear(d_model, d_ff),
            ReLU(),
            Linear(d_ff, d_model)
        )

    def forward(self, x):
        return self.net(x)

class SpanRepresentation(nn.Module):
    def __init__(self, d_model, d_ff):
        super().__init__()
        self.net = Sequential(
            Linear(2 * d_model, d_ff),
            ReLU(),
            Linear(d_ff, d_model)
        )

    def forward(self, start_token, end_token):
        span = torch.cat([start_token, end_token], dim=-1)
        return self.net(span)

class Sigmoid(nn.Module):
    def forward(self, x):
        return 1 / (1 + torch.exp(-x))

class Matching(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, entity, span):
        entity = entity.transpose(-1, -2)
        output = span @ entity
        return output

class Decoder(nn.Module):
    def __init__(self, entity_types, threshold=0.5, mode="flat"):
        super().__init__()
        self.entity_types = entity_types
        self.threshold = threshold
        self.mode = mode

    def overlapping(self, span1, span2):
        s1, e1 = span1
        s2, e2 = span2
        return not (e1 < s2 or e2 < s1)

    def partial_overlap(self, span1, span2):
        s1, e1 = span1
        s2, e2 = span2

        overlap = not (e1 < s2 or e2 < s1)
        if not overlap:
            return False

        nested = (s1 <= s2 and e2 <= e1) or (s2 <= s1 and e1 <= e2)
        return not nested

    def decode_one(self, probs, span_indices):
        candidates = []
        n_span, n_ent = probs.shape

        for n in range(n_span):
            s, e = span_indices[n]
            for ent_idx in range(n_ent):
                score = probs[n, ent_idx].item()
                if score > self.threshold:
                    candidates.append({
                        "start": s,
                        "end": e,
                        "label": self.entity_types[ent_idx],
                        "score": score
                    })

        candidates.sort(key=lambda x: x["score"], reverse=True)

        selected = []
        for cand in candidates:
            c_span = (cand["start"], cand["end"])
            conflict = False

            for sel in selected:
                p_span = (sel["start"], sel["end"])
                if self.mode == "flat":
                    if self.overlapping(c_span, p_span):
                        conflict = True
                        break
                elif self.mode == "nested":
                    if self.partial_overlap(c_span, p_span):
                        conflict = True
                        break

            if not conflict:
                selected.append(cand)

        return selected

    def decode_batch(self, probs_batch, span_indices_batch):
        results = []
        for probs, span_indices in zip(probs_batch, span_indices_batch):
            results.append(self.decode_one(probs, span_indices))
        return results

class GLiNER(nn.Module):
    def __init__(self, backbone_model, entity_types, d_ff, max_span_width=10, threshold=0.5, mode="flat"):
        super().__init__()

        self.entity_types = entity_types
        self.num_entity_types = len(entity_types)
        self.max_span_width = max_span_width

        self.encoder = EncoderModule(backbone_model)
        d_model = self.encoder.hidden_size

        self.word_rep = WordTokenRepresentation(pooling="mean")
        self.ent_token_rep = ENTTokenRepresentation()

        self.ent_rep = EntityRepresentation(d_model, d_ff)
        self.span_rep = SpanRepresentation(d_model, d_ff)

        self.sigmoid = Sigmoid()
        self.matching = Matching()

        self.decoder = Decoder(
            entity_types=entity_types,
            threshold=threshold,
            mode=mode
        )

    def build_span_representation(self, word_embeddings, word_len):
        B, _, H = word_embeddings.shape

        batch_span_vectors = []
        batch_span_indices = []

        for b in range(B):
            w_len = word_len[b].item()
            cur_words = word_embeddings[b]

            starts = []
            ends = []
            span_indices = []

            for start in range(w_len):
                max_end = min(w_len, start + self.max_span_width)
                for end in range(start, max_end):
                    starts.append(start)
                    ends.append(end)
                    span_indices.append((start, end))

            if len(span_indices) == 0:
                span_vecs = torch.zeros(0, H, device=word_embeddings.device, dtype=word_embeddings.dtype)
            else:
                start_embs = cur_words[starts]
                end_embs = cur_words[ends]
                span_vecs = self.span_rep(start_embs, end_embs)

            batch_span_vectors.append(span_vecs)
            batch_span_indices.append(span_indices)

        return batch_span_vectors, batch_span_indices

    def forward(self, input_ids, attention_mask, text_mask, ent_mask, word_index):
        hidden_states = self.encoder(input_ids, attention_mask)

        word_embeddings, word_len = self.word_rep(
            hidden_states=hidden_states,
            text_mask=text_mask,
            word_index=word_index
        )

        ent_embeddings, ent_valid_mask = self.ent_token_rep(hidden_states, ent_mask)
        ent_vectors = self.ent_rep(ent_embeddings)

        span_vectors_batch, span_indices_batch = self.build_span_representation(word_embeddings, word_len)

        logits_batch = []
        for b in range(input_ids.size(0)):
            span_vec = span_vectors_batch[b]
            ent_vec = ent_vectors[b].unsqueeze(0)
            logits = self.matching(ent_vec, span_vec).squeeze(0)
            logits_batch.append(logits)

        return logits_batch, span_indices_batch

    @torch.no_grad()
    def predict(self, input_ids, attention_mask, text_mask, ent_mask, word_index):
        self.eval()
        logits_batch, span_indices_batch = self.forward(
            input_ids=input_ids,
            attention_mask=attention_mask,
            text_mask=text_mask,
            ent_mask=ent_mask,
            word_index=word_index
        )
        probs_batch = [self.sigmoid(x) for x in logits_batch]
        results = self.decoder.decode_batch(probs_batch, span_indices_batch)
        return results

def build_inference_features(tokens, tokenizer, entity_types, max_length=512):
    text_enc = tokenizer(
        tokens,
        is_split_into_words=True,
        add_special_tokens=False
    )

    text_input_ids = text_enc["input_ids"]
    text_word_ids = text_enc.word_ids()

    entity_input_ids = []
    entity_ent_mask = []

    for ent in entity_types:
        ent_enc = tokenizer(ent, add_special_tokens=False)
        ent_ids = ent_enc["input_ids"]

        for j, tid in enumerate(ent_ids):
            entity_input_ids.append(tid)
            entity_ent_mask.append(1 if j == 0 else 0)

    cls_id = tokenizer.cls_token_id
    sep_id = tokenizer.sep_token_id

    input_ids = [cls_id] + text_input_ids + [sep_id] + entity_input_ids + [sep_id]
    attention_mask = [1] * len(input_ids)
    text_mask = [0] + [1] * len(text_input_ids) + [0] + [0] * len(entity_input_ids) + [0]
    ent_mask = [0] + [0] * len(text_input_ids) + [0] + entity_ent_mask + [0]
    word_index = [-1] + [wid if wid is not None else -1 for wid in text_word_ids] + [-1] + [-1] * len(entity_input_ids) + [-1]

    if len(input_ids) > max_length:
        input_ids = input_ids[:max_length]
        attention_mask = attention_mask[:max_length]
        text_mask = text_mask[:max_length]
        ent_mask = ent_mask[:max_length]
        word_index = word_index[:max_length]

    return {
        "input_ids": torch.tensor([input_ids], dtype=torch.long),
        "attention_mask": torch.tensor([attention_mask], dtype=torch.long),
        "text_mask": torch.tensor([text_mask], dtype=torch.long),
        "ent_mask": torch.tensor([ent_mask], dtype=torch.long),
        "word_index": torch.tensor([word_index], dtype=torch.long),
        "tokens": tokens
    }

# =========================================================
# 5. GlobalPointer
# =========================================================
class SinusoidalPositionEmbedding(nn.Module):
    def __init__(self, output_dim, merge_mode="zero"):
        super().__init__()
        self.output_dim = output_dim
        self.merge_mode = merge_mode

    def forward(self, inputs):
        batch_size, seq_len = inputs.shape[:2]
        device = inputs.device

        position_ids = torch.arange(0, seq_len, dtype=torch.float, device=device).unsqueeze(-1)
        indices = torch.arange(0, self.output_dim // 2, dtype=torch.float, device=device)
        indices = torch.pow(10000.0, -2 * indices / self.output_dim)

        embeddings = position_ids * indices
        embeddings = torch.stack([torch.sin(embeddings), torch.cos(embeddings)], dim=-1)
        embeddings = embeddings.reshape(seq_len, self.output_dim)
        embeddings = embeddings.unsqueeze(0).repeat(batch_size, 1, 1)

        if self.merge_mode == "zero":
            return embeddings
        elif self.merge_mode == "add":
            return inputs + embeddings
        else:
            raise ValueError("merge_mode must be 'zero' or 'add'")

def apply_rope(x, pos):
    cos_pos = pos[..., 1::2].repeat_interleave(2, dim=-1).unsqueeze(2)
    sin_pos = pos[..., ::2].repeat_interleave(2, dim=-1).unsqueeze(2)

    x2 = torch.stack([-x[..., 1::2], x[..., ::2]], dim=-1)
    x2 = x2.reshape_as(x)

    return x * cos_pos + x2 * sin_pos

class GlobalPointer(nn.Module):
    def __init__(self, encoder_name: str, ent_type_size: int, inner_dim: int = 64):
        super().__init__()
        self.encoder = AutoModel.from_pretrained(encoder_name)
        self.ent_type_size = ent_type_size
        self.inner_dim = inner_dim
        self.hidden_size = self.encoder.config.hidden_size

        self.dense = nn.Linear(self.hidden_size, ent_type_size * inner_dim * 2)
        self.position_embedding = SinusoidalPositionEmbedding(inner_dim, merge_mode="zero")

    def forward(self, input_ids, attention_mask):
        outputs = self.encoder(input_ids=input_ids, attention_mask=attention_mask)
        last_hidden_state = outputs.last_hidden_state

        logits = self.dense(last_hidden_state)
        logits = torch.split(logits, self.inner_dim * 2, dim=-1)
        logits = torch.stack(logits, dim=-2)

        qw, kw = logits[..., :self.inner_dim], logits[..., self.inner_dim:]

        pos = self.position_embedding(last_hidden_state)
        qw = apply_rope(qw, pos)
        kw = apply_rope(kw, pos)

        logits = torch.einsum("bmhd,bnhd->bhmn", qw, kw)

        pad_mask = attention_mask.unsqueeze(1).unsqueeze(1) * attention_mask.unsqueeze(1).unsqueeze(2)
        logits = logits * pad_mask - (1 - pad_mask) * 1e12

        lower_mask = torch.tril(torch.ones_like(logits), diagonal=-1)
        logits = logits - lower_mask * 1e12

        return logits / (self.inner_dim ** 0.5)

# =========================================================
# 6. 체크포인트 로드 함수
# =========================================================
def safe_load_checkpoint(path, device="cpu"):
    if not os.path.exists(path):
        raise FileNotFoundError(f"파일이 없습니다: {path}")
    return torch.load(path, map_location=device)

def safe_load_state_dict_into_model(model, checkpoint):
    if isinstance(checkpoint, dict):
        if "model_state_dict" in checkpoint:
            model.load_state_dict(checkpoint["model_state_dict"], strict=False)
        elif "state_dict" in checkpoint:
            model.load_state_dict(checkpoint["state_dict"], strict=False)
        else:
            model.load_state_dict(checkpoint, strict=False)
    else:
        model.load_state_dict(checkpoint, strict=False)

# =========================================================
# 7. 모델 로드
# =========================================================
print("🧠 모델 가중치 장착 중...")

# 7-1. CRF
model_crf = BertCRF("klue/bert-base", num_classes=NUM_CRF_CLASSES)
ckpt_crf = safe_load_checkpoint("best_bert_crf.pt", device=device)
safe_load_state_dict_into_model(model_crf, ckpt_crf)
model_crf.to(device)
model_crf.eval()

# 7-2. GLiNER
model_gliner = GLiNER(
    backbone_model="klue/bert-base",
    entity_types=ENTITY_TYPES,
    d_ff=256,             # 네 체크포인트 shape 기준
    max_span_width=10,
    threshold=0.5,
    mode="flat"
)
ckpt_gliner = safe_load_checkpoint("best_gliner.pt", device=device)
safe_load_state_dict_into_model(model_gliner, ckpt_gliner)
model_gliner.to(device)
model_gliner.eval()

# 7-3. GlobalPointer
model_gp = GlobalPointer(
    encoder_name="klue/bert-base",
    ent_type_size=len(ENTITY_TYPES),   # 6
    inner_dim=64
)

ckpt_gp = safe_load_checkpoint("bert_globalpointer_ner_best.pt", device=device)
if isinstance(ckpt_gp, dict) and "model_state_dict" in ckpt_gp:
    state_dict_gp = ckpt_gp["model_state_dict"]
else:
    state_dict_gp = ckpt_gp

new_state_dict_gp = {}
for key, value in state_dict_gp.items():
    new_key = key.replace("global_pointer.dense", "dense")
    new_state_dict_gp[new_key] = value

model_gp.load_state_dict(new_state_dict_gp, strict=False)
model_gp.to(device)
model_gp.eval()

print("✅ 모델 로드 완료")

# =========================================================
# 8. 데이터셋 로드
# =========================================================
print("📥 평가 데이터 로드 중...")
dataset = []
with open("preprocessed_1000_bio_valid.jsonl", "r", encoding="utf-8") as f:
    for line in f:
        dataset.append(json.loads(line))

print("샘플 수:", len(dataset))

# =========================================================
# 9. 변환 함수
# =========================================================
def span_to_bio(text_length, spans):
    bio = ["O"] * text_length

    for span in spans:
        start, end, label = span["start"], span["end"], span["label"]

        if start >= text_length:
            continue

        bio[start] = f"B-{label}"

        # GLiNER의 span end를 포함하는 방식
        for i in range(start + 1, min(end + 1, text_length)):
            bio[i] = f"I-{label}"

    return bio

def token_preds_to_char_bio(offsets, pred_ids, text_length):
    pred_bio = ["O"] * text_length

    usable_len = min(len(offsets), len(pred_ids))
    for idx in range(usable_len):
        start, end = offsets[idx]
        if start == end:
            continue

        tag = id2label.get(pred_ids[idx], "O")
        if tag == "O":
            continue

        if start < text_length:
            pred_bio[start] = tag

        inside_tag = tag.replace("B-", "I-")
        for char_idx in range(start + 1, min(end, text_length)):
            pred_bio[char_idx] = inside_tag

    return pred_bio

def globalpointer_to_bio(scores, offsets, text_length, threshold=0.0):
    pred_bio = ["O"] * text_length

    candidates = []
    for label_id, start_tok, end_tok in zip(*np.where(scores > threshold)):
        if label_id >= len(ENTITY_TYPES):
            continue
        if start_tok >= len(offsets) or end_tok >= len(offsets):
            continue

        char_start = offsets[start_tok][0]
        char_end = offsets[end_tok][1]

        if char_start == char_end:
            continue
        if char_start >= text_length:
            continue

        score = scores[label_id, start_tok, end_tok]
        candidates.append((score, label_id, char_start, char_end))

    # 점수 높은 순으로 정렬
    candidates.sort(key=lambda x: x[0], reverse=True)

    occupied = [False] * text_length

    for score, label_id, char_start, char_end in candidates:
        # 이미 다른 span이 차지한 구간이면 스킵
        overlap = False
        for i in range(char_start, min(char_end, text_length)):
            if occupied[i]:
                overlap = True
                break
        if overlap:
            continue

        label = ENTITY_TYPES[label_id]
        pred_bio[char_start] = f"B-{label}"
        for i in range(char_start + 1, min(char_end, text_length)):
            pred_bio[i] = f"I-{label}"

        for i in range(char_start, min(char_end, text_length)):
            occupied[i] = True

    return pred_bio

# =========================================================
# 10. 평가 루프
# =========================================================
all_true_bio = []
all_pred_crf = []
all_pred_gliner = []
all_pred_gp = []

print("🚀 3개 모델 동시 추론 시작!")

for data in tqdm(dataset):
    tokens = data["tokens"]
    raw_true_bio = data["bio_tags"]

    # 15개 valid 라벨 중 6개 엔티티만 남김
    true_bio = filter_bio_tags_to_target_entities(raw_true_bio, ENTITY_TYPES)

    text = "".join(tokens)
    text_length = len(tokens)

    all_true_bio.append(true_bio)

    # -----------------------------
    # 공통 입력 (CRF / GP)
    # -----------------------------
    inputs = tokenizer(
        text,
        return_tensors="pt",
        max_length=128,
        truncation=True,
        return_offsets_mapping=True
    )

    offsets = inputs["offset_mapping"][0].cpu().numpy()

    model_inputs = {
        "input_ids": inputs["input_ids"].to(device),
        "attention_mask": inputs["attention_mask"].to(device)
    }

    # -----------------------------
    # 1) CRF
    # -----------------------------
    with torch.no_grad():
        _, predictions = model_crf(
            input_ids=model_inputs["input_ids"],
            attention_mask=model_inputs["attention_mask"]
        )

    pred_ids_crf = predictions[0]
    pred_bio_crf = token_preds_to_char_bio(offsets, pred_ids_crf, text_length)
    all_pred_crf.append(pred_bio_crf)

    # -----------------------------
    # 2) GLiNER
    # -----------------------------
    features = build_inference_features(tokens, tokenizer, ENTITY_TYPES)

    with torch.no_grad():
        pred_spans_gliner = model_gliner.predict(
            input_ids=features["input_ids"].to(device),
            attention_mask=features["attention_mask"].to(device),
            text_mask=features["text_mask"].to(device),
            ent_mask=features["ent_mask"].to(device),
            word_index=features["word_index"].to(device)
        )

    pred_bio_gliner = span_to_bio(text_length, pred_spans_gliner[0])
    all_pred_gliner.append(pred_bio_gliner)

    # -----------------------------
    # 3) GlobalPointer
    # -----------------------------
    with torch.no_grad():
        logits = model_gp(
            model_inputs["input_ids"],
            model_inputs["attention_mask"]
        )

    scores = logits[0].detach().cpu().numpy()
    pred_bio_gp = globalpointer_to_bio(scores, offsets, text_length, threshold=0.0)
    all_pred_gp.append(pred_bio_gp)

# =========================================================
# 11. 평가 출력
# =========================================================
def print_detailed_metrics(true_bio, pred_bio, model_name, icon):
    p = precision_score(true_bio, pred_bio)
    r = recall_score(true_bio, pred_bio)
    f = f1_score(true_bio, pred_bio)

    tp, fp, fn = 0, 0, 0
    for t_seq, p_seq in zip(true_bio, pred_bio):
        t_ents = set(get_entities(t_seq))
        p_ents = set(get_entities(p_seq))

        tp += len(t_ents & p_ents)
        fp += len(p_ents - t_ents)
        fn += len(t_ents - p_ents)

    print(f"{icon} [{model_name}]")
    print(f"   Precision : {p:.4f}")
    print(f"   Recall    : {r:.4f}")
    print(f"   F1        : {f:.4f}")
    print(f"   TP={tp}, FP={fp}, FN={fn}")
    print("-" * 60)

print("\n" + "=" * 60)
print("🏆 6개 엔티티 기준 일반화 평가 결과")
print("=" * 60)

print_detailed_metrics(all_true_bio, all_pred_crf, "CRF", "🟢")
print_detailed_metrics(all_true_bio, all_pred_gliner, "GLiNER", "🔵")
print_detailed_metrics(all_true_bio, all_pred_gp, "GlobalPointer", "🔴")

print("\n[CRF classification report]")
print(classification_report(all_true_bio, all_pred_crf, digits=4))

print("\n[GLiNER classification report]")
print(classification_report(all_true_bio, all_pred_gliner, digits=4))

print("\n[GlobalPointer classification report]")
print(classification_report(all_true_bio, all_pred_gp, digits=4))